export enum ELeaveType {
  ANNUEL = 'ANNUEL',
  MALADIE = 'MALADIE',
  MATERNITE = 'MATERNITÉ',
  PATERNITE = 'PATERNITÉ',
  SANS_SOLDE = 'SANS_SOLDE',
  DECES = 'DÉCÈS',
  TELETRAVAIL = 'TÉLÉTRAVAIL',
  AUTORISATION = 'AUTORISATION',
}
